[package]
name = "alqs_cli"
description = "CLI for ALQS database"
version = "0.1.0"
edition = "2021"
license-file = "../LICENSE"

[[bin]]
name = "alqs"
path = "src/main.rs"

[dependencies]
alqs_shared = "0.1"
clap = { version = "4.4.11", features = ["derive"] }
